/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAddNewMember.java
 *
 * Created on Jul 16, 2011, 9:56:54 AM
 */
package pharmasoft.ui;


import pharmasoft.ui.util.UiSupliment;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import pharmasoft.db.model.Supplier;
import pharmasoft.db.dao.CommonDAO;
import pharmasoft.db.dao.ProductDAO;
import pharmasoft.db.model.Customer;
import pharmasoft.db.model.Product;
import pharmasoft.util.StringFormatter;

public class FrmAddNewProductBatch extends javax.swing.JInternalFrame {

    /** Creates new form FrmAddNewMember */
//    public FrmAddNewMember() {
//        initComponents();
//    }
    private int supplierId;
    private int productId;

    private CommonDAO commonDAO;
    private ProductDAO productDAO;

    public int getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    
    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public FrmAddNewProductBatch(Dimension innerPannel) {
        initComponents();
        commonDAO = new CommonDAO();
        productDAO = new ProductDAO();
        Dimension localFrm = UiSupliment.getFormLocation(innerPannel, this.getSize());
        this.setClosable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setLocation((int) localFrm.getWidth(), (int) localFrm.getHeight());
        this.txtSupplierE.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        this.txtProNameE.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnEdit1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        lblAddress1 = new javax.swing.JLabel();
        txtWholeSalePriceE = new javax.swing.JTextField();
        lblTelNo1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtUnitsizeE = new javax.swing.JTextField();
        txtDiscountE = new javax.swing.JTextField();
        txtRetailPriceE = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        txtProNameE = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        txtProDescE = new javax.swing.JTextField();
        lblAddress4 = new javax.swing.JLabel();
        lblAddress5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSupplierE = new javax.swing.JTextField();

        setResizable(true);
        setTitle("Add New Product Batch");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEdit1.setText("Exit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        lblAddress1.setText("Unit Size");

        txtWholeSalePriceE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWholeSalePriceEFocusLost(evt);
            }
        });
        txtWholeSalePriceE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWholeSalePriceEKeyPressed(evt);
            }
        });

        lblTelNo1.setText("Whole Sale Price");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtUnitsizeE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitsizeEActionPerformed(evt);
            }
        });
        txtUnitsizeE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnitsizeEFocusLost(evt);
            }
        });
        txtUnitsizeE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnitsizeEKeyPressed(evt);
            }
        });

        txtDiscountE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscountEFocusLost(evt);
            }
        });
        txtDiscountE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscountEKeyPressed(evt);
            }
        });

        txtRetailPriceE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRetailPriceEFocusLost(evt);
            }
        });
        txtRetailPriceE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetailPriceEKeyPressed(evt);
            }
        });

        lblName3.setText("Product Name");

        txtProNameE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProNameEActionPerformed(evt);
            }
        });
        txtProNameE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProNameEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProNameEFocusLost(evt);
            }
        });
        txtProNameE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProNameEKeyPressed(evt);
            }
        });

        lblName5.setText("Product description");

        txtProDescE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProDescEActionPerformed(evt);
            }
        });
        txtProDescE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProDescEFocusLost(evt);
            }
        });
        txtProDescE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProDescEKeyPressed(evt);
            }
        });

        lblAddress4.setText("Discount");

        lblAddress5.setText("Retail Price");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Supplier");

        txtSupplierE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierEActionPerformed(evt);
            }
        });
        txtSupplierE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierEKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblTelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress1)
                                    .addComponent(lblAddress4)
                                    .addComponent(lblName5)
                                    .addComponent(lblName3)
                                    .addComponent(lblAddress5)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDiscountE, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUnitsizeE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtWholeSalePriceE, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRetailPriceE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtProNameE, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnSearch))
                            .addComponent(txtProDescE, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSupplierE, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProNameE)
                    .addComponent(lblName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblName5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(txtProDescE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitsizeE)
                    .addComponent(lblAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiscountE)
                    .addComponent(lblAddress4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetailPriceE)
                    .addComponent(lblAddress5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWholeSalePriceE)
                    .addComponent(lblTelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtWholeSalePriceEKeyPressed(java.awt.event.KeyEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int res = JOptionPane.showConfirmDialog(rootPane, "Do You Want To Add New Batch for this Product?", 
                "Confirmation!", JOptionPane.YES_NO_OPTION);

        if (res == 0) {
            String proName = txtProNameE.getText();
            String proDesc = txtProDescE.getText();
            String unitSize = txtUnitsizeE.getText();
            String discount = txtDiscountE.getText();
            String retailPrice = txtRetailPriceE.getText();
            String wholePrice = txtWholeSalePriceE.getText();
            int supplierId = getSupplierId();
            int proId = getProductId();
            
            Product product = new Product();
            product.setProductId(proId);
            product.setProductName(proName);
            product.setProductDesc(proDesc);
            product.setUnitSize(Integer.parseInt(unitSize));
            if (discount != null && !discount.isEmpty())
                product.setDiscount(Integer.parseInt(discount));
            product.setRetailPrice(StringFormatter.rupeesToLong(retailPrice));
            product.setWholeSalePrice(StringFormatter.rupeesToLong(wholePrice));
            product.setSupplierId(supplierId);
            
      

            boolean flag = false;
            try {
                flag = productDAO.addNewBatchProduct(product);
            } catch (SQLException ex) {
                Logger.getLogger(FrmAddNewProductBatch.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (flag) {
                JOptionPane.showConfirmDialog(rootPane, "Add New Batch Successfully!", 
                        "Success!", JOptionPane.CLOSED_OPTION);
                this.frmSetClear();
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Add New Batch Failed!", 
                        "Failed!", JOptionPane.CLOSED_OPTION);
            }

        }
    }                                         

    private void txtUnitsizeEActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtUnitsizeEFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtUnitsizeEKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtDiscountEFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtDiscountEKeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtRetailPriceEFocusLost(java.awt.event.FocusEvent evt) {                                          
        long retailPrice = StringFormatter.rupeesToLong(txtRetailPriceE.getText());
        txtRetailPriceE.setText(StringFormatter.formatToRupees(retailPrice));
    }                                         

    private void txtRetailPriceEKeyPressed(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txtProNameEActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtProNameEFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void txtProNameEKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            FrmSearchBox frmSearchBox = new FrmSearchBox(this);
            frmSearchBox.setValue("p.pro_name", "productSearch");
            frmSearchBox.setVisible(true);
            frmSearchBox.setLocation(200, 300);
        }
    }                                      

    private void txtProDescEActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtProDescEFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void txtProDescEKeyPressed(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtSupplierEActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        FrmSearchBox frmSearchBox = new FrmSearchBox(this);
        frmSearchBox.setValue("p.pro_name", "productSearch");
        frmSearchBox.setVisible(true);
        frmSearchBox.setLocation(200, 300);
    }                                         

    private void txtProNameEFocusGained(java.awt.event.FocusEvent evt) {                                        
        int proId = getProductId();
        Product product = commonDAO.getProductDetails(proId, 0);
        if (product != null) {
            txtProDescE.setText(product.getProductDesc());
            txtUnitsizeE.setText(String.valueOf(product.getUnitSize()));
            txtDiscountE.setText(String.valueOf(product.getDiscount()));
            txtRetailPriceE.setText(StringFormatter.formatToRupees(product.getRetailPrice()));
            txtWholeSalePriceE.setText(String.valueOf(product.getWholeSalePrice()));
            Supplier supplier = commonDAO.getSupplierDetailsById(product.getSupplierId());
            if (supplier != null)
                txtSupplierE.setText(supplier.getSupplierName());
            else
                txtSupplierE.setText("");
        }
    }                                       

    private void txtSupplierEKeyPressed(java.awt.event.KeyEvent evt) {                                        
     if (evt.getKeyCode() == KeyEvent.VK_F4) {
            FrmSearchBox frmSearchBox = new FrmSearchBox(this);
            frmSearchBox.setValue("s.supplier_name", "supplierSearch");
            frmSearchBox.setVisible(true);
            frmSearchBox.setLocation(200, 300);
        }
    }                                       

    private void txtWholeSalePriceEFocusLost(java.awt.event.FocusEvent evt) {                                             
        long wholeSalePrice = StringFormatter.rupeesToLong(txtWholeSalePriceE.getText());
        txtWholeSalePriceE.setText(StringFormatter.formatToRupees(wholeSalePrice));
    }                                            

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblAddress5;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblTelNo1;
    private javax.swing.JTextField txtDiscountE;
    private javax.swing.JTextField txtProDescE;
    public javax.swing.JTextField txtProNameE;
    private javax.swing.JTextField txtRetailPriceE;
    protected javax.swing.JTextField txtSupplierE;
    private javax.swing.JTextField txtUnitsizeE;
    private javax.swing.JTextField txtWholeSalePriceE;
    // End of variables declaration                   

    private void frmSetClear() {
        txtDiscountE.setText("");
        txtRetailPriceE.setText("");
        txtWholeSalePriceE.setText("");
        txtUnitsizeE.setText("");
        txtProNameE.setText("");
        txtProDescE.setText("");
        txtSupplierE.setText("");       
    }

    private void frmEditSetClear() {
//        txtFirstNameE.setText("");
//        txtLastNameE.setText("");
//        txtAddLine1E.setText("");
//        txtAddLine2E.setText("");
//        txtAddLine3E.setText("");
//        txtTelNoE.setText("");
//        txtFaxNoE.setText("");
    }
}
