/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmBatchProTable.java
 *
 * Created on May 24, 2015, 1:34:03 AM
 */
package pharmasoft.ui;

import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import pharmasoft.db.proxyClasses.ProductBatchProxy;
import pharmasoft.util.StringFormatter;

/**
 *
 * @author Vipula
 */
public class FrmBatchProTable extends javax.swing.JDialog  {
    JInternalFrame internalFrame;
    private int productId;
    private String productName;

    public JInternalFrame getInternalFrame() {
        return internalFrame;
    }

    public void setInternalFrame(JInternalFrame internalFrame) {
        this.internalFrame = internalFrame;
    }
    
    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }
    
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }


    
    /** Creates new form FrmBatchProTable */
    public FrmBatchProTable() {
        initComponents();

    }
    
    public FrmBatchProTable(JInternalFrame internalFrame, Vector<ProductBatchProxy> resBatch) {
        initComponents();
        this.setInternalFrame(internalFrame);
        this.setLocation(400, 300);
        
                
        DefaultTableModel model = (DefaultTableModel) tblBatchPro.getModel();
        for (Iterator<ProductBatchProxy> it = resBatch.iterator(); it.hasNext();) {
            ProductBatchProxy productBatchProxy = it.next();
            this.setProductId(productBatchProxy.getProductId());
            this.setProductName(productBatchProxy.getProductName());
            model.addRow(new Object[]{productBatchProxy.getBatchId(), StringFormatter.formatToRupees(productBatchProxy.getRetailPrice()), 
                StringFormatter.formatToRupees(productBatchProxy.getWholeSalePrice()), productBatchProxy.getUnitInStock()});
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBatchPro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBatchPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BATCH ID", "RETAIL PRICE", "WHOLE SALE PRICE", "UNIT INSTOCK", "EXPIRE DATE"
            }
        ));
        tblBatchPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblBatchProKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBatchPro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void tblBatchProKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int[] selRows = tblBatchPro.getSelectedRows();
                Object value = null;
                Object id = null;
                if (selRows.length > 0) {
                    for (int i = 0; i < selRows.length; i++) {
                        TableModel tm = tblBatchPro.getModel();
                        value = tm.getValueAt(selRows[0], i + 1);
                        id = tm.getValueAt(selRows[0], i);
                    }
                    setFormdata(Integer.parseInt(id.toString()));
                }
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();;
            }
        }
    }                                      

    public void setFormdata(int id) {
        if (this.getInternalFrame() instanceof FrmTransaction) {
            FrmTransaction frmTransaction = (FrmTransaction) this.getInternalFrame();
            frmTransaction.setBatchId(id);
            frmTransaction.setProductId(getProductId());
            frmTransaction.txtProductCode.setText(getProductName());
        } else if (this.getInternalFrame() instanceof FrmPurchaseOrder) {
            FrmPurchaseOrder frmPurchaseOrder = (FrmPurchaseOrder) this.getInternalFrame();
//            frmPurchaseOrder.setBatchId(id);
            frmPurchaseOrder.setProductId(getProductId());
            frmPurchaseOrder.txtProductCode.setText(getProductName());
        }  else if (this.getInternalFrame() instanceof FrmWholeSaleTransaction) {
            FrmWholeSaleTransaction frmWholeSaleTran = (FrmWholeSaleTransaction) this.getInternalFrame();
            frmWholeSaleTran.setBatchId(id);
            frmWholeSaleTran.setProductId(getProductId());
            frmWholeSaleTran.txtProductCode.setText(getProductName());
        }
    }
    

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmBatchProTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBatchPro;
    // End of variables declaration                   
}
