/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmInvoiceDetail.java
 *
 * Created on Nov 1, 2015, 11:46:14 AM
 */
package pharmasoft.ui;

import java.awt.Component;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import pharmasoft.db.dao.ProductDAO;
import pharmasoft.db.proxyClasses.ProductBatchProxy;
import pharmasoft.db.proxyClasses.TransDetailsProxy;
import pharmasoft.ui.util.UiSupliment;
import pharmasoft.util.StringFormatter;

/**
 *
 * @author Vipula
 */
public class FrmInvoiceDetail extends javax.swing.JDialog {

    private int invoiceId;
    ProductDAO productDAO;
    
    /** Creates new form FrmInvoiceDetail */
    public FrmInvoiceDetail(JInternalFrame parent, boolean modal, int invoiceId) {
//        super(parent, modal);
        Dimension localFrm = UiSupliment.getInnerFormLocation(parent, this.getSize());
        this.setLocation((int) localFrm.getWidth(), (int) localFrm.getHeight());
        initComponents();
        
        setInvoiceId(invoiceId);
        productDAO = new ProductDAO();
        populateInvoiceDetails();
    }
    
    public void populateInvoiceDetails(){
        DefaultTableModel model = (DefaultTableModel) tblInvoiceDet.getModel();
        model.getDataVector().removeAllElements();
        tblInvoiceDet.repaint();
        Vector<TransDetailsProxy> proDetails = productDAO.getProDetailsByInvoiceId(getInvoiceId());
        if (proDetails != null && !proDetails.isEmpty()) {
            for (Iterator<TransDetailsProxy> it = proDetails.iterator(); it.hasNext();) {
                TransDetailsProxy proxy = it.next();
                model.addRow(new Object[]{proxy.getProductName(), proxy.getUnitSize(), StringFormatter.formatToRupees(proxy.getUnitPrice()), 
                    proxy.getQuentity(), StringFormatter.formatToRupees(proxy.getSubTotal())});
//                            StringFormatter.formatToRupees(proxy.get)});
//                renderer.setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
//                rendererL.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
//                tblTrans.getColumnModel().getColumn(0).setCellRenderer(renderer);
//                tblTrans.getColumnModel().getColumn(1).setCellRenderer(renderer);
//                tblTrans.getColumnModel().getColumn(2).setCellRenderer(rendererL);
//                tblTrans.getColumnModel().getColumn(3).setCellRenderer(renderer);
//                tblTrans.getColumnModel().getColumn(4).setCellRenderer(renderer);
                tblInvoiceDet.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                lblInvoiceNo.setText(String.valueOf(proxy.getInvoiceId()));
                lblTimeStamp.setText(new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(proxy.getTimeStamp()));
                lblTotalAmt.setText(StringFormatter.formatToRupees(proxy.getGrandTotal()));
            }
        }
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoiceDet = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);
                int rendererWidth = component.getPreferredSize().width;
                TableColumn tableColumn = getColumnModel().getColumn(column);
                tableColumn.setPreferredWidth(Math.max(rendererWidth + getIntercellSpacing().width, tableColumn.getPreferredWidth()));
                return component;
            }
        };
        tblInvoiceDet.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jLabel1 = new javax.swing.JLabel();
        lblInvoiceNo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTimeStamp = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTotalAmt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoice Details");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblInvoiceDet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblInvoiceDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT NAME", "UNIT SIZE", "RETAIL PRICE", "QUANTITY", "VALUE"
            }
        ));
        jScrollPane2.setViewportView(tblInvoiceDet);

        jLabel1.setText("Invoice / Recipt No");

        jLabel2.setText("Date and Time");

        btnPrint.setText("Print");
        btnPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.setMaximumSize(new java.awt.Dimension(65, 23));
        btnPrint.setMinimumSize(new java.awt.Dimension(65, 23));

        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel3.setText("Total Amount");

        lblTotalAmt.setFont(new java.awt.Font("Times New Roman", 1, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimeStamp, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(lblInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(593, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(lblTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnPrint});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(lblTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnPrint});

        pack();
    }// </editor-fold>                        

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
}                                         

    
    public int getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(int invoiceId) {
        this.invoiceId = invoiceId;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                FrmInvoiceDetail dialog = new FrmInvoiceDetail(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblTimeStamp;
    private javax.swing.JLabel lblTotalAmt;
    public javax.swing.JTable tblInvoiceDet;
    // End of variables declaration                   
}
