/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPayment.java
 *
 * Created on Feb 12, 2015, 9:47:22 PM
 */
package pharmasoft.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pharmasoft.db.dao.CommonDAO;
import pharmasoft.db.dao.TransactionDAO;
import pharmasoft.db.proxyClasses.TransDetailsProxy;
import pharmasoft.db.proxyClasses.TransPurchDetailsProxy;
import pharmasoft.ui.util.UiSupliment;
import pharmasoft.util.StringFormatter;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Vipula
 */
public class FrmPayment extends javax.swing.JDialog {
    
    private CommonDAO commonDAO;
    private TransactionDAO transDAO;
    private Object frmType;
    private long grandTotal;
    private long balance;
    private List<TransDetailsProxy> tableRowContent;

    public List<TransDetailsProxy> getTableRowContent() {
        return tableRowContent;
    }

    public void setTableRowContent(List<TransDetailsProxy> tableRowContent) {
        this.tableRowContent = tableRowContent;
    }

    /** Creates new form FrmPayment */
    public FrmPayment(long subTotal, List<TransDetailsProxy> tableRowContent, Object frmType) {
        initComponents();
        commonDAO = new CommonDAO();
        transDAO = new TransactionDAO();
        this.setTableRowContent(tableRowContent);
        this.setModal(true);
        this.setLocation(500, 330);
        this.grandTotal = subTotal;
        this.lblGrandTotal.setText(StringFormatter.formatToRupees(subTotal));
        this.frmType = frmType;
        this.setFrmComponents(frmType);
 
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGrandTotal = new javax.swing.JLabel();
        lblRAmount = new javax.swing.JLabel();
        lblBal = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtReceivedAmount = new javax.swing.JTextField();
        lblPayType = new javax.swing.JLabel();
        cmbPayType = new javax.swing.JComboBox();
        lblChqNo = new javax.swing.JLabel();
        txtChequeNo = new javax.swing.JTextField();
        lblChqDate = new javax.swing.JLabel();
        jChqDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAYMENTS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 150));

        lblGrandTotal.setFont(new java.awt.Font("Times New Roman", 1, 18));

        lblRAmount.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblRAmount.setText("Received Amount");

        lblBal.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblBal.setText("Balance");

        lblBalance.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel4.setText("Grand Total");

        txtReceivedAmount.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtReceivedAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReceivedAmountKeyPressed(evt);
            }
        });

        lblPayType.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblPayType.setText("Payment Type");

        cmbPayType.setModel(new DefaultComboBoxModel(new String[] {"Cash", "Cheque", "Credit"}));
        cmbPayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPayTypeActionPerformed(evt);
            }
        });
        cmbPayType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbPayTypeKeyPressed(evt);
            }
        });

        lblChqNo.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblChqNo.setText("Cheque No");

        txtChequeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChequeNoActionPerformed(evt);
            }
        });
        txtChequeNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChequeNoKeyPressed(evt);
            }
        });

        lblChqDate.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblChqDate.setText("Cheque Date");

        jChqDate.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPayType)
                    .addComponent(lblRAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChqNo)
                    .addComponent(lblChqDate)
                    .addComponent(lblBal))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChequeNo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPayType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReceivedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPayType, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReceivedAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChqNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChequeNo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChqDate, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jChqDate, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblBal, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbPayType, jChqDate, lblBalance, lblGrandTotal, txtChequeNo, txtReceivedAmount});

        jPanel2.setPreferredSize(new java.awt.Dimension(318, 30));

        btnOk.setText("OK");
        btnOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOkKeyPressed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnOk});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void txtReceivedAmountKeyPressed(java.awt.event.KeyEvent evt) {                                             
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            long receivedAmount = 0;
//            if (frmType instanceof FrmWholeSaleTransaction) {
//               btnOk.requestFocus();
//            } else 
            if (txtReceivedAmount.getText() != null && !txtReceivedAmount.getText().isEmpty()) {
                receivedAmount = StringFormatter.rupeesToLong(txtReceivedAmount.getText());
                txtReceivedAmount.setText(StringFormatter.formatToRupees(receivedAmount));
                if (receivedAmount > grandTotal) {
                    balance = receivedAmount - grandTotal;
                    lblBalance.setText(StringFormatter.formatToRupees(balance));
                } else {
                    JOptionPane.showMessageDialog(this, "Not sufficiant amount.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                btnOk.requestFocus();
            }
        }
    }                                            

    private void btnOkKeyPressed(java.awt.event.KeyEvent evt) {                                 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          insertTransaction();
        }
    }                                

    private void insertTransaction() {
        boolean flag = false;
        try {
            if (frmType instanceof FrmTransaction) {
//                flag = transDAO.insertTransaction(this.grandTotal, this.getTableRowContent());
            } else if (frmType instanceof FrmWholeSaleTransaction) {
                FrmWholeSaleTransaction frm = (FrmWholeSaleTransaction) frmType;
                flag = transDAO.inserWholeSaleTrans(this.grandTotal, this.getTableRowContent(), frm.getCustomerId());               
            } else if (frmType instanceof FrmPurchaseOrder) {
                TransPurchDetailsProxy proxy = new TransPurchDetailsProxy();
                proxy.setGrandTotal(this.grandTotal);
                proxy.setPayType(cmbPayType.getSelectedItem().toString());
                if ("Cheque".equals(cmbPayType.getSelectedItem().toString())) {
                    proxy.setChqNo(Long.parseLong(txtChequeNo.getText()));
                    proxy.setChqDate(jChqDate.getDate());
                }
                flag = transDAO.insertPurchaseTrans(proxy, this.getTableRowContent());
            }
            
            if (flag) {
                JOptionPane.showConfirmDialog(rootPane, "Added Successfully!", "Success!", JOptionPane.CLOSED_OPTION);
                dispose();
                clearTrnTable();
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Failed!", "Failed!", JOptionPane.CLOSED_OPTION);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmAddNewProductBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void clearTrnTable() {
        DefaultTableModel model = null;
        int rowCount = 0;
        if (frmType instanceof FrmTransaction) {
            FrmTransaction frmTrn = (FrmTransaction) frmType;
            model = (DefaultTableModel) frmTrn.tblTransaction.getModel();
            rowCount = model.getRowCount();
            frmTrn.txtProductCode.requestFocus();
        } else if (frmType instanceof FrmPurchaseOrder) {
            FrmPurchaseOrder frmTrn = (FrmPurchaseOrder) frmType;
            model = (DefaultTableModel) frmTrn.tblTransaction.getModel();
            rowCount = model.getRowCount();
            frmTrn.txtProductCode.requestFocus();
        } else if (frmType instanceof FrmWholeSaleTransaction) {
            FrmWholeSaleTransaction frmTrn = (FrmWholeSaleTransaction) frmType;
            model = (DefaultTableModel) frmTrn.tblTransaction.getModel();
            rowCount = model.getRowCount();
            frmTrn.txtProductCode.requestFocus();
        }
        
        for (int i = rowCount - 1 ; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    
    private void setFrmComponents(Object frmType){
        cmbPayType.setVisible(false);
        jChqDate.setVisible(false);
        lblBal.setVisible(false);
        lblBalance.setVisible(false);
        lblChqDate.setVisible(false);
        lblChqNo.setVisible(false);
        lblPayType.setVisible(false);
        lblRAmount.setVisible(false);
        txtChequeNo.setVisible(false);
        txtReceivedAmount.setVisible(false);
//        if (frmType instanceof FrmTransaction || frmType instanceof FrmWholeSaleTransaction) {
        if (frmType instanceof FrmWholeSaleTransaction) {
        	lblPayType.setVisible(true);
        	cmbPayType.setVisible(true);
        	cmbPayType.setSelectedItem("Credit");
        } else if (frmType instanceof FrmPurchaseOrder) {
            lblPayType.setVisible(true);
            cmbPayType.setVisible(true);
        } 
    }
    private void txtChequeNoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

	private void cmbPayTypeActionPerformed(java.awt.event.ActionEvent evt) {
		if ("Cheque".equals(cmbPayType.getSelectedItem())) {
			lblChqNo.setVisible(true);
			txtChequeNo.setVisible(true);
			lblChqDate.setVisible(true);
			jChqDate.setVisible(true);
			
			lblRAmount.setVisible(false);
			txtReceivedAmount.setVisible(false);
			lblBal.setVisible(false);
			lblBalance.setVisible(false);
		} else if ("Cash".equals(cmbPayType.getSelectedItem())) {
			lblRAmount.setVisible(true);
			txtReceivedAmount.setVisible(true);
			lblBal.setVisible(true);
			lblBalance.setVisible(true);
			
			lblChqNo.setVisible(false);
			txtChequeNo.setVisible(false);
			lblChqDate.setVisible(false);
			jChqDate.setVisible(false);
		} else {
			lblChqNo.setVisible(false);
			txtChequeNo.setVisible(false);
			lblChqDate.setVisible(false);
			jChqDate.setVisible(false);
			
			lblRAmount.setVisible(false);
			txtReceivedAmount.setVisible(false);
			lblBal.setVisible(false);
			lblBalance.setVisible(false);
		}
	}                                         

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
            dispose();
    }                                         

    private void cmbPayTypeKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("Cash".equals(cmbPayType.getSelectedItem()))
                btnOk.requestFocus();
            else
                txtChequeNo.requestFocus();
        }
    }                                     

    private void txtChequeNoKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jChqDate.requestFocus();      
        }
    }                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbPayType;
    private com.toedter.calendar.JDateChooser jChqDate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBal;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblChqDate;
    private javax.swing.JLabel lblChqNo;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblPayType;
    private javax.swing.JLabel lblRAmount;
    private javax.swing.JTextField txtChequeNo;
    private javax.swing.JTextField txtReceivedAmount;
    // End of variables declaration                   
}
