/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaginationBox.java
 *
 * Created on Oct 13, 2015, 11:05:20 PM
 */
package pharmasoft.ui;

import pharmasoft.ui.FrmStockTaking.SysAction;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;

/**
 *
 * @author Vipula
 */
public class PaginationBox extends javax.swing.JPanel implements PaginationListner{

    private int noOfPages;

    /** Creates new form PaginationBox */
    public PaginationBox() {
        initComponents();
        txtNoOfPages.setName("txtNoOfPages");
        txtCurrentPage.setName("txtCurrentPage");
        btnNext.setName("btnNext");
        btnPrevious.setName("btnPrevious");
        btnFirst.setName("btnFirst");
        btnLast.setName("btnLast");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCurrentPage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNoOfPages = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        btnFirst.setText("<<");
        btnFirst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPrevious.setText("<");
        btnPrevious.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Page");

        jLabel2.setText("Of");

        btnNext.setText(">");
        btnNext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLast.setText(">>");
        btnLast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(btnFirst, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnPrevious, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtCurrentPage, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtNoOfPages, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        			.addGap(32)
        			.addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnLast, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        			.addComponent(btnFirst, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addComponent(btnPrevious, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addComponent(btnLast, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addComponent(jLabel1)
        			.addComponent(txtCurrentPage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addComponent(jLabel2)
        			.addComponent(txtNoOfPages, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        this.setLayout(layout);
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCurrentPage;
    public javax.swing.JTextField txtNoOfPages;
    // End of variables declaration                   

    public int getNoOfPages() {
        return noOfPages;
    }

    public void setNoOfPages(int noOfPages) {
        this.noOfPages = noOfPages;
    }

    @Override
    public void setCurrentPage() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void navigateToNext() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void navigateToPrevious() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void navigateToFirst() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void navigateToLast() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
}
